version: "3.9"

x-airflow-common: &airflow-common
  build:
    context: .           
    dockerfile: Dockerfile
  image: airflow-dbt:2.9.3
  env_file:
    - .env
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${PG_AIRFLOW_USER}:${PG_AIRFLOW_PASSWORD}@postgres/${PG_AIRFLOW_DB}
    - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
    - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    - DBT_PROFILES_DIR=/opt/airflow/dbt_project
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./yorb_dbt:/opt/airflow/dbt_project
    - ../dbt.json:/opt/airflow/gcp-key.json:ro
  user: "${AIRFLOW_UID:-50000}:0"
  networks:
    - airflow_net

services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${PG_AIRFLOW_USER}
      - POSTGRES_PASSWORD=${PG_AIRFLOW_PASSWORD}
      - POSTGRES_DB=${PG_AIRFLOW_DB}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - airflow_net
    healthcheck:
      test: "pg_isready -U ${PG_AIRFLOW_USER}"
      interval: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    depends_on:
      - postgres
    command: db init

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    depends_on:
      - postgres
    command: webserver
    ports:
      - "8080:8080"
    restart: unless-stopped

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    depends_on:
      - postgres
    command: scheduler
    restart: unless-stopped

volumes:
  postgres-db-volume:

networks:
  airflow_net:
    driver: bridge
